# Generated by Django 4.2.7 on 2023-11-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diapede', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes',
            name='Percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
